# Configuração do Nginx para servir a aplicação React
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Se o arquivo solicitado não for encontrado, redireciona para index.html
        try_files $uri $uri/ /index.html;
    }
}